### ISSUE TITLE
Lovely!

### ISSUE THREAD

**Issue by wiseman** [EngineersNeedArt/Mooncraft2000#2]
Just wanted to say this is a fun, lovely little game and I enjoyed the discussion of implementation and various tradeoffs (engineering-wise and design-wise) in the README.

**Comment by EngineersNeedArt** [comment]
Thank you. It's helpful to see what people enjoy. I'll spend more time on that sort of thing in the future — talking about how I created it.

I'll try to add some pages on the topic to my blog over the coming weeks/months.
